demo_app/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

demo_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

demo_app/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('app/views/say/*')
  end

  def goodbye
  end
end

demo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

demo_app/app/helpers/say_helper.rb
module SayHelper
end

demo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

demo_app/app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
  It was nice having you here.
</p>
<p>
  <%= link_to "Say 'hello!'", say_hello_path %>
</p>

demo_app/app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>It's now: <%= @time %></p>
<p>
  Time to say
  <%= link_to "Goodbye", say_goodbye_path %>
</p>

<h2>Playtime</h2>
<p>Addition: <%= 1 + 2 %></p>
<p>Concatenation: <%= 'cow' + 'boy' %></p>
<p>Time in one hour: <%= 1.hour.from_now.localtime %></p>
<p><%= @files %></p>
<div class="files">
  <h3>Files in app/views/say/</h3>
  <ul>
  <% @files.each do |file| %>
    <li><i>file name is:</i> "<%= file %>"</li>
  <% end %>
  </ul>
</div>